### ISSUE TITLE
Restore data by xMatters/xmtoolbox 

### ISSUE THREAD

**Issue by od260470** [brannonvann/xmtoolbox-quick-start#12]
Hello,

I got backup file from our xMatters non-prod instance-1 by run Backup.js, changed the name of Group, shifts of this Group and Users.
I used the script Restore.js and got the errors for all devices that has type of "Voice" and those devices weren't created.
Example of the error:
statusCode: 400,
 data: `{"code":400,"message":"The provider field must contain a valid id value. For devices of type VOICE, valid id values include the following:  '(x)MattersVoiceXML - Voxeo Test' '(x)Matters Voice Gateway (Voxeo)' '(x)Matters Voice Gateway (Voxeo - No Retry)' '(x)Matters Voice Gateway' '(x)Matters SIP Gateway'.","reason":"Bad Request","subcode":"validation.device.must_specify_provider","arguments":["VOICE"," '(x)MattersVoiceXML - Voxeo Test' '(x)Matters Voice Gateway (Voxeo)' '(x)Matters Voice Gateway (Voxeo - No Retry)' '(x)Matters Voice Gateway' '(x)Matters SIP Gateway'"]}`,
  
  The parameter "Provider ID" is located in the backup file but I got that error.
  
  I did the same on another of our non-prod instance-2 and the new group, shifts, users are created without any errors.
  
  The differences between those instances is that
  -  non-prod instance-1 has 5 providers
  - non-prod instance- 2 has 1 provider.
  
  I submitted the request to xMatters (#550460) and got the below response:
  "I believe the backup file has the information but the actual xMToolbox code to restore is not sending that information along based on what Paul was saying in this ticket. You would need to modify the code to include the provider in the payload using the data from your backup file. Alternatively you can request this is updated via the github page and one of the consultants who owns this tool can make the changes."
  Please, check it and let me know if you need more details.

**Comment by od260470** [comment]
Hello, is it possible to get any response for my question?
Have you had a chance to look on it or read at least.
Thank you so much in advance for any reaction!

**Comment by hmiedema9** [comment]
Hi there,
We have read your request, but we are a bit short staffed on xmtoolbox supporters. We will look into it further as quickly as possible.

**Comment by hmiedema9** [comment]
I saw on your xMatters support request that you got this solved by adding the name of a provider:

"provider": {
               "id": "(x)Matters Voice Gateway (Voxeo - No Retry)"
           }

Did this not work?

**Comment by od260470** [comment]
Hello Hayden, thank you for the response!
It's working when I POST request through Postman. But when I had been using xmtoolbox it didn't work even the provider id information is in the backup.json file, for example:

{
      "id": "xxxxxxxxxxxxxxxxxxxxxxxx",
      "name": "Work Phone",
      "phoneNumber": "+19999999999",
      "targetName": "ABC_Test_User1|Work Phone",
      "deviceType": "VOICE",
      "description": "(999)9999999",
      "testStatus": "UNTESTED",
      "externallyOwned": false,
      "externalKey": "ABC_Test_User1|Work Phone",
      "defaultDevice": true,
      "priorityThreshold": "LOW",
      "sequence": 2,
      "delay": 0,
      "timeframes": {
        "count": 1,
        "total": 1,
        "data": [
          {
            "name": "Work Phone - Default 24 x 7",
            "startTime": "00:00",
            "timezone": "US/Eastern",
            "durationInMinutes": 1440,
            "excludeHolidays": false,
            "days": [
              "SU",
              "MO",
              "TU",
              "WE",
              "TH",
              "FR",
              "SA"
            ]
          }
        ],
        "links": {
          "self": "/api/xm/1/devices/xxxxxxxxxxxxxxxxxxxxxxxx/timeframes?offset=0&limit=100"
        }
      },
      "owner": {
        "id": "xxxxxxxxxxxxxxxxxxxxxxxx",
        "targetName": "ABC_Test_User1",
        "firstName": "ABC Test",
        "lastName": "User",
        "licenseType": "FULL_USER",
        "recipientType": "PERSON",
        "links": {
          "self": "/api/xm/1/people/xxxxxxxxxxxxxxxxxxxxxxxx"
        }
      },
      "links": {
        "self": "/api/xm/1/devices/xxxxxxxxxxxxxxxxxxxxxxxx"
      },
      "privileged": false,
      "country": "US",
      "recipientType": "DEVICE",
      "status": "ACTIVE",
      "provider": {
        "id": "(x)Matters Voice Gateway (Voxeo - No Retry)"
      }
    },


The same format of data is working for our instance that has one provider for device type=VOICE.

**Comment by hmiedema9** [comment]
Got it, thank you for the info. I am going to respond to the xmatters
ticket when I am back at my desk and ask you for a little bit more info. Is
it okay if I do testing directly with your environment?

**Comment by od260470** [comment]
Sure, those instances are non-prod.

**Comment by hmiedema9** [comment]
Hi Olga,
I've got this fixed locally. Working on getting it shipped out to NPM in a new xmtoolbox version. I'll let you know when it is published.

**Comment by hmiedema9** [comment]
Hi,
The fix is now published in xmtoolbox version 1.2.31. You can update your package by simply running `npm update` in the directory of your project.

I am going to close the issue. Reopen it or open a new issue if you still experience problems

**Comment by od260470** [comment]
It's working now!
Thank you, Hayden! 

With regards, Olga.
